### ISSUE TITLE
Mt Moon

### ISSUE THREAD

**Issue by irrefragable** [g0ldPRO/Questing.lua#7] opened 2016-06-16 23:41 UTC
The bot just go in and out of the mt moon without doing anything after my pokemon got the right level. I tried many times.

**Comment by irrefragable** [comment] 2016-06-17 11:41
I fixed it by going manually to the B2F and then restarting to use the script.

**Comment by irrefragable** [comment] 2016-06-17 11:46
I fixed it by going manually to the B2F and then restarting to use the script.

**Comment by g0ldPRO** [comment] 2016-06-17 15:09
I am currently adding the PC support to the PROShine API. After what I will release a new Questing.lua version including a fix for this bug.

**Comment by g0ldPRO** [comment] 2016-06-18 13:59
Duplicate of #4

**Closed as completed by g0ldPRO** 2016-06-18 13:59 UTC
Labels: duplicate
